apiVersion: v1
kind: Secret
metadata:
  name: api
  labels:
    {{- include "avatar.labels" . | nindent 4 }}
type: Opaque

data:
  pepper: {{ .Values.api.pepper | b64enc | quote }}
  authjwt_secret_key: {{ .Values.api.authjwtSecretKey | b64enc | quote }}
  file_encryption_key: {{ .Values.api.fileEncryptionKey | b64enc | quote }}
  organization_name: {{ .Values.api.organizationName | b64enc | quote }}
  avatar_first_user_name: {{ .Values.api.firstUserName | b64enc | quote }}
  avatar_first_user_password: {{ .Values.api.firstUserPassword | b64enc | quote }}
  admin_emails: {{ join "," .Values.api.adminEmails | b64enc | quote }}
  db_name: {{ .Values.dbName | b64enc | quote }}
  db_user: {{ .Values.dbUsername | b64enc | quote }}
  db_password: {{ .Values.dbPassword | b64enc | quote }}
  aws_mail_account_access_key_id: {{ .Values.api.awsMailAccountAccessKeyId | b64enc | quote }}
  aws_mail_account_secret_access_key: {{ .Values.api.awsMailAccountSecretAccessKey | b64enc | quote }}
  aws_storage_account_access_key_id: {{ .Values.api.awsStorageAccountAccessKeyId | b64enc | quote }}
  aws_storage_account_secret_access_key: {{ .Values.api.awsStorageAccountSecretAccessKey | b64enc | quote }}
  clevercloud_sso_salt: {{ .Values.api.clevercloudSsoSalt | b64enc | quote }}