apiVersion: v1
kind: Secret
metadata:
  name: docker-local-pull-secret
  labels:
    {{- include "avatar.labels" . | nindent 4 }}

data:
  .dockerconfigjson: {{ .Values.dockerPullSecret }}

type: kubernetes.io/dockerconfigjson
